# Generated by Django 4.2.15 on 2024-11-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_specialhours_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="open_from",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_until",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
