# Generated by Django 5.2.7 on 2025-10-08 18:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contractitem',
            name='days',
        ),
        migrations.RemoveField(
            model_name='contractitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='contractitem',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='used',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 8, 18, 49, 32, 438398, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 8, 18, 49, 34, 928150, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractitem',
            name='item_name',
            field=models.CharField(default='Товар', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contract'),
        ),
    ]
