# Generated by Django 5.2.7 on 2025-10-08 19:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 19, 0, 49, 84669, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(default=datetime.datetime(2025, 10, 8, 19, 1, 0, 578707, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='rental.contract'),
        ),
    ]
