# Generated by Django 5.2.7 on 2025-10-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_contract_signed_otp_expire_at_otp_phone_otp_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='used',
        ),
    ]
